### ISSUE TITLE
 No such file or directory: '../DAMSMencoders/fashiongen2/text_encoder80.pth'

### ISSUE THREAD

**Issue by Bowenwu1** [menardai/FashionGenAttnGAN#1]
While pretraining DAMSM, the above error occured, would you tell me how to solve it ? Thank you very much!

**Comment by menardai** [comment]
Please create an empty folder name 'fashiongen2' under 'DAMSMencoders'.

**Comment by Bowenwu1** [comment]
`
Load from:  ../data/fashiongen/captions2_attngan.pickle
2932 1
Load from:  ../data/fashiongen/captions2_attngan.pickle
/data/wubowen/FashionGenAttnGAN/fashion/local/lib/python2.7/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
('Load pretrained model from ', 'https://download.pytorch.org/models/inception_v3_google-1a9a5a14.pth')
Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 266, in <module>
    text_encoder, image_encoder, labels, start_epoch = build_models()
  File "pretrain_DAMSM.py", line 170, in build_models
    state_dict = torch.load(cfg.TRAIN.NET_E)
  File "/data/wubowen/FashionGenAttnGAN/fashion/local/lib/python2.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: '../DAMSMencoders/fashiongen2/text_encoder80.pth'
`

**Comment by Bowenwu1** [comment]
I have tried above solution, but it doesn't work.

**Comment by Bowenwu1** [comment]
I changed some config on yml file and it worked. Thanks a lot.

**Comment by lean1606** [comment]
@Bowenwu1 can you teach me how to fix that issue please ? thanks a lot..
